import React from 'react'
import Header from '../../modules/components/globals/Header'
import Head from 'next/head'

export default function BeerName(props) {

    return (
        <>
            <Head>
                <title>Beer Name</title>
                <meta name="description" content="Generated by remixrty" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
                <link rel="icon" href="/beer_ico.png" />
            </Head>
            <Header />
            <a>Hello beer</a>
        </>
    )
}