import Head from 'next/head'
import Header from '../modules/components/globals/Header'
import Mainpage from '../modules/components/mainpage/Mainpage'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Beer Market</title>
        <meta name="description" content="Generated by remixrty" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
        <link rel="icon" href="/beer_ico.png" />
        
      </Head>

      <main className={styles.main}>
        <Header />
        <Mainpage />
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
